# Generated by Django 5.0.6 on 2024-06-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_assign_date',
            field=models.DateField(),
        ),
    ]
