# Generated by Django 5.0.6 on 2024-06-26 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumb_name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('reting', models.PositiveSmallIntegerField()),
                ('musician', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musician.musician')),
            ],
        ),
    ]
