# Generated by Django 5.0.6 on 2024-06-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumb', '0002_rename_reting_albumb_rating_alter_albumb_musician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumb',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
    ]
