# Generated by Django 5.0.6 on 2024-06-26 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumb', '0001_initial'),
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumb',
            old_name='reting',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='albumb',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumbs', to='musician.musician'),
        ),
    ]
